def main():
    print("Hello I am Himanshu,")
    input()
    print("This is just a test file for the git")
    input()
    print("I hope everything will go fine")
    input()
    print("Yes it is working fine.")
    name = input("Enter your name: ")
    print("hello"+name)
if __name__ == "__main__":main()